export const GET_DATA = 'GET_DATA';
export const LOAD_DATA = 'LOAD_DATA';
export const ELECTED_ITEM = 'ELECTED_ITEM';
export const SELECT_FROM_LEFT_ITEM = 'SELECT_FROM_LEFT_ITEM';
export const SELECT_FROM_RIGHT_ITEM = 'SELECT_FROM_RIGHT_ITEM';
